// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/my_jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{my_jwt.AuthMiddleware.MiddlewareFunc()}
}

func _deletecommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{my_jwt.AuthMiddleware.MiddlewareFunc()}
}

func _likesMw() []app.HandlerFunc {
	return []app.HandlerFunc{my_jwt.AuthMiddleware.MiddlewareFunc()}
}

func _likeactionMw() []app.HandlerFunc {
	return []app.HandlerFunc{my_jwt.AuthMiddleware.MiddlewareFunc()}
}

func _getlikelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _video_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
