// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/my_jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadvideoMw() []app.HandlerFunc {
	return []app.HandlerFunc{my_jwt.AuthMiddleware.MiddlewareFunc()}
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuservideosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethotvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}
