services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: video_web
      MYSQL_ROOT_PASSWORD: zhangqi20060212
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads