// Code generated by hertz generator.

package main

import (
	handler "VideoWeb/biz/handler"
	userHandler "VideoWeb/biz/handler/user/example"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	api := r.Group("/api")
	api.POST("/sessions/refresh", userHandler.RefreshSession)
	api.DELETE("/sessions", userHandler.Logout)
}
