// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	"VideoWeb/biz/my_jwt"
	"context"
	"net/http"

	format "VideoWeb/biz/handler/common_response_format"
	example0 "VideoWeb/biz/model/common/example"
	example "VideoWeb/biz/model/user/example"

	"github.com/cloudwego/hertz/pkg/app"
	"golang.org/x/crypto/bcrypt"
)

func dealRegister(c *app.RequestContext, request *example.UserRegisterRequest) bool {
	if len(request.Password) < 8 {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "密码小于8位！！！")
		return false
	}

	if len(request.Nickname) == 0 {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "昵称为空！！！")
		return false
	}

	if len(request.Username) == 0 {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "无用户名输入！！！")
		return false
	}

	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(request.Password), bcrypt.DefaultCost)
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PROGRESS_ERROR, "密码加密过程出错")
		return false
	}
	request.Password = string(hashedPassword)
	//写入数据库
	db := mysql.GetDB()
	//没有指明table的话会默认把结构体的名称作为表名
	result := db.Table("users").Create(&request)
	if result.Error != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, result.Error.Error())
		return false
	}
	return true
}

// Register .
// @router /api/users [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.UserRegisterRequest
	err = c.BindForm(&req)
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}
	if !dealRegister(c, &req) {
		return
	} else {
		keyword := "register"
		format.Success(c, keyword, nil)
	}
}

// Login .
// @router /api/sessions [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	my_jwt.AuthMiddleware.LoginHandler(ctx, c)
}
