// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	format "VideoWeb/biz/handler/common_response_format"
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	example0 "VideoWeb/biz/model/common/example"
	example "VideoWeb/biz/model/video/example"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/google/uuid"
	"github.com/hertz-contrib/jwt"
)

// UploadVideo .
// @router /api/videos [POST]
func UploadVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.UploadVideoRequest
	claims := jwt.ExtractClaims(ctx, c)
	tokenUserID, ok := claims["ID"].(float64)
	if !ok {
		format.Fail(c, http.StatusUnauthorized, example0.ErrorCode_USER_NOT_LOGIN, "id is not included int token")
		return
	}
	userID := int64(tokenUserID)
	err = c.BindForm(&req)
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	if req.Title == "" || req.Description == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "视频标题或描述不能为空")
		return
	}

	videoHeader, err := c.FormFile("file")
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, "未收到视频文件")
		return
	}

	videoExt := strings.ToLower(filepath.Ext(videoHeader.Filename))
	allowedVideoExts := map[string]bool{
		".mp4":  true,
		".avi":  true,
		".mov":  true,
		".mkv":  true,
		".wmv":  true,
		".flv":  true,
		".webm": true,
	}
	if !allowedVideoExts[videoExt] {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_VIDEO_FORMAT_ERROR, "不支持的视频格式，仅支持 mp4/avi/mov/mkv/wmv/flv/webm")
		return
	}

	if videoHeader.Size > 500*1024*1024 {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "视频大小不能超过500MB")
		return
	}

	videoDir := "./uploads/videos"
	if err := os.MkdirAll(videoDir, 0755); err != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "创建目录失败")
		return
	}

	videoFilename := fmt.Sprintf("%d_%s%s", time.Now().Unix(), uuid.New().String()[:8], videoExt)
	videoPath := filepath.Join(videoDir, videoFilename)

	if err := c.SaveUploadedFile(videoHeader, videoPath); err != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "保存视频失败")
		return
	}

	videoURL := fmt.Sprintf("http://localhost:8888/videos/%s", videoFilename)

	video := mysql.Videos{
		UserID:      userID,
		Title:       req.Title,
		Description: req.Description,
		VideoURL:    videoURL,
		Views:       0,
		Likes:       0,
	}

	db := mysql.GetDB()
	if err := db.Table("videos").Create(&video).Error; err != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "创建视频记录失败")
		return
	}

	format.Success(c, "uploadVideo", video)
}
