// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	format "VideoWeb/biz/handler/common_response_format"
	"context"
	"fmt"
	"net/http"

	example0 "VideoWeb/biz/model/common/example"
	example "VideoWeb/biz/model/social/example"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetFollowList .
// @router /api/users/:user_id/followings [GET]
func GetFollowList(ctx context.Context, c *app.RequestContext) {
	var req example.FollowListRequest
	if err := c.BindAndValidate(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	userIDStr := c.Param("user_id")
	if userIDStr == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "用户ID不能为空")
		return
	}

	var userID int64
	if _, err := fmt.Sscanf(userIDStr, "%d", &userID); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "无效的用户ID")
		return
	}

	page := int(req.Page)
	pageSize := int(req.PageSize)
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 50 {
		pageSize = 10
	}

	db := mysql.GetDB()

	var total int64
	db.Model(&mysql.Follows{}).Where("follower_id = ?", userID).Count(&total)

	var follows []mysql.Follows
	offset := (page - 1) * pageSize
	if err := db.Where("follower_id = ?", userID).
		Order("created_at DESC").
		Offset(offset).Limit(pageSize).
		Find(&follows).Error; err != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "查询失败")
		return
	}

	if len(follows) == 0 {
		format.Success(c, "followList", map[string]interface{}{
			"items": []interface{}{},
			"total": 0,
		})
		return
	}

	followingIDs := make([]int64, len(follows))
	for i, f := range follows {
		followingIDs[i] = f.FollowingID
	}

	var users []mysql.Users
	db.Table("users").
		Select("id, username, avatar_url, nickname, created_at").
		Where("id IN (?)", followingIDs).
		Find(&users)

	userMap := make(map[int64]mysql.Users)
	for _, u := range users {
		userMap[int64(u.ID)] = u
	}

	items := make([]map[string]interface{}, 0, len(follows))
	for _, f := range follows {
		if u, ok := userMap[f.FollowingID]; ok {
			items = append(items, map[string]interface{}{
				"id":          u.ID,
				"username":    u.Username,
				"nickname":    u.Nickname,
				"avatar_url":  u.Avatarurl,
				"followed_at": f.CreatedAt,
			})
		}
	}

	format.Success(c, "followList", map[string]interface{}{
		"items": items,
		"total": total,
	})
}

// GetFollowerList .
// @router /api/users/:user_id/followers [GET]
func GetFollowerList(ctx context.Context, c *app.RequestContext) {
	var req example.FollowerListRequest
	if err := c.BindAndValidate(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	userIDStr := c.Param("user_id")
	if userIDStr == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "用户ID不能为空")
		return
	}

	var userID int64
	if _, err := fmt.Sscanf(userIDStr, "%d", &userID); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "无效的用户ID")
		return
	}

	page := int(req.Page)
	pageSize := int(req.PageSize)
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 50 {
		pageSize = 10
	}

	db := mysql.GetDB()

	var total int64
	db.Model(&mysql.Follows{}).Where("following_id = ?", userID).Count(&total)

	var follows []mysql.Follows
	offset := (page - 1) * pageSize
	if err := db.Where("following_id = ?", userID).
		Order("created_at DESC").
		Offset(offset).Limit(pageSize).
		Find(&follows).Error; err != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "查询失败")
		return
	}

	if len(follows) == 0 {
		format.Success(c, "followerList", map[string]interface{}{
			"items": []interface{}{},
			"total": 0,
		})
		return
	}

	followerIDs := make([]int64, len(follows))
	for i, f := range follows {
		followerIDs[i] = f.FollowerID
	}

	var users []mysql.Users
	db.Table("users").
		Select("id, username, avatar_url, nickname, created_at").
		Where("id IN (?)", followerIDs).
		Find(&users)

	userMap := make(map[int64]mysql.Users)
	for _, u := range users {
		userMap[int64(u.ID)] = u
	}

	items := make([]map[string]interface{}, 0, len(follows))
	for _, f := range follows {
		if u, ok := userMap[f.FollowerID]; ok {
			items = append(items, map[string]interface{}{
				"id":          u.ID,
				"username":    u.Username,
				"nickname":    u.Nickname,
				"avatar_url":  u.Avatarurl,
				"followed_at": f.CreatedAt,
			})
		}
	}

	format.Success(c, "followerList", map[string]interface{}{
		"items": items,
		"total": total,
	})
}
