// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	common_example "VideoWeb/biz/router/common/example"
	interaction_example "VideoWeb/biz/router/interaction/example"
	social_example "VideoWeb/biz/router/social/example"
	user_example "VideoWeb/biz/router/user/example"
	video_example "VideoWeb/biz/router/video/example"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	social_example.Register(r)

	interaction_example.Register(r)

	video_example.Register(r)

	user_example.Register(r)

	common_example.Register(r)
}
