// Code generated by hertz generator.

package main

import (
	"VideoWeb/biz/dal/mysql"
	"VideoWeb/biz/my_jwt"
	"VideoWeb/biz/router"
	"log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	if err := my_jwt.InitJWT(); err != nil {
		log.Fatal("JWT初始化失败:", err)
	}
	db := mysql.InitDB()
	defer db.Close()
	h := server.Default(server.WithMaxRequestBodySize(500 * 1024 * 1024))
	h.StaticFS("/avatars", &app.FS{
		Root:        "./uploads/avatars",
		PathRewrite: app.NewPathSlashesStripper(1), // 去掉第一级路径
	})
	router.GeneratedRegister(h)

	h.Spin()
}
