// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	"VideoWeb/biz/dal/redis"
	"VideoWeb/biz/my_jwt"
	"context"
	"net/http"
	"strconv"

	format "VideoWeb/biz/handler/common_response_format"
	example0 "VideoWeb/biz/model/common/example"
	example "VideoWeb/biz/model/user/example"

	"github.com/cloudwego/hertz/pkg/app"
	"golang.org/x/crypto/bcrypt"
)

func dealRegister(c *app.RequestContext, request *example.UserRegisterRequest) bool {
	if len(request.Password) < 8 {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "密码小于8位！！！")
		return false
	}

	if len(request.Nickname) == 0 {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "昵称为空！！！")
		return false
	}

	if len(request.Username) == 0 {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "无用户名输入！！！")
		return false
	}

	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(request.Password), bcrypt.DefaultCost)
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PROGRESS_ERROR, "密码加密过程出错")
		return false
	}

	db := mysql.GetDB()
	var count int64
	db.Table("users").Where("username = ?", request.Username).Count(&count)
	if count > 0 {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "用户名已存在")
		return false
	}

	user := mysql.Users{
		Username: request.Username,
		Password: string(hashedPassword),
		Nickname: request.Nickname,
	}
	result := db.Create(&user)
	if result.Error != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, result.Error.Error())
		return false
	}

	redis.AddToBloomFilter("user", strconv.FormatUint(uint64(user.ID), 10))

	return true
}

// Register .
// @router /api/users [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.UserRegisterRequest
	err = c.BindForm(&req)
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}
	if !dealRegister(c, &req) {
		return
	} else {
		keyword := "register"
		format.Success(c, keyword, nil)
	}
}

// Login .
// @router /api/sessions [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	my_jwt.AuthMiddleware.LoginHandler(ctx, c)
}
