// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	"VideoWeb/biz/dal/redis"
	format "VideoWeb/biz/handler/common_response_format"
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	example0 "VideoWeb/biz/model/common/example"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/google/uuid"
	"github.com/hertz-contrib/jwt"
)

// GetUserInfo .
// @router /api/users/:user_id [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	id := c.Param("user_id")
	cacheKey := "user:info:" + id

	var userinfo mysql.Users
	err := redis.GetJSON(cacheKey, &userinfo)
	if err == nil && userinfo.Username != "" {
		format.Success(c, "getInfo", userinfo)
		return
	}

	db := mysql.GetDB()
	db.Table("users").
		Select("id, username, avatar_url, created_at, updated_at, nickname, deleted_at").
		Where("id = ?", id).
		First(&userinfo)
	if userinfo.Username == "" {
		format.Fail(c, http.StatusNotFound, example0.ErrorCode_PARAM_ERROR, "id is not exist")
		return
	}

	redis.SetJSON(cacheKey, userinfo, 30*time.Minute)

	format.Success(c, "getInfo", userinfo)
}

// UploadAvatar .
// @router /api/users/:user_id/avatar [POST]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	userIDStr := c.Param("user_id")
	if userIDStr == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "用户ID不能为空")
		return
	}
	var frontendUserID int64
	if _, err := fmt.Sscanf(userIDStr, "%d", &frontendUserID); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "无效的用户ID")
		return
	}

	claims := jwt.ExtractClaims(ctx, c)
	tokenUserID, ok := claims["ID"].(float64)
	if !ok {
		format.Fail(c, http.StatusUnauthorized, example0.ErrorCode_PARAM_ERROR, "Token中缺少用户ID")
		return
	}

	if int64(tokenUserID) != frontendUserID {
		format.Fail(c, http.StatusForbidden, example0.ErrorCode_PARAM_ERROR, "没有权限修改其他用户的头像")
		return
	}
	handleAvatarUpload(ctx, c, int64(tokenUserID))
}

func handleAvatarUpload(ctx context.Context, c *app.RequestContext, userID int64) {
	header, err := c.FormFile("file")
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, "未收到文件: "+err.Error())
		return
	}

	if header.Size > 2*1024*1024 {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, "文件大小不能超过2MB")
		return
	}

	ext := strings.ToLower(filepath.Ext(header.Filename))
	allowedExts := map[string]bool{".jpg": true, ".jpeg": true, ".png": true, ".gif": true, ".webp": true}
	if !allowedExts[ext] {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, "只支持 jpg、png、gif、webp 格式")
		return
	}

	uploadDir := "./uploads/avatars"
	if err := os.MkdirAll(uploadDir, 0755); err != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "创建目录失败")
		return
	}

	db := mysql.GetDB()
	var oldUser mysql.Users
	db.First(&oldUser, userID)

	if oldUser.Avatarurl != "" {
		oldFilename := filepath.Base(oldUser.Avatarurl)
		oldFilePath := filepath.Join(uploadDir, oldFilename)

		if err := os.Remove(oldFilePath); err != nil && !os.IsNotExist(err) {
			log.Printf("删除旧头像失败: %v", err)
		}
	}

	filename := fmt.Sprintf("%d_%s%s", time.Now().Unix(), uuid.New().String()[:8], ext)
	filePath := filepath.Join(uploadDir, filename)

	if err := c.SaveUploadedFile(header, filePath); err != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "保存文件失败: "+err.Error())
		return
	}

	avatarURL := fmt.Sprintf("http://localhost:8888/avatars/%s", filename)

	result := db.Table("users").Where("id = ?", userID).Update("avatar_url", avatarURL)
	if result.Error != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "更新头像URL失败")
		return
	}

	cacheKey := "user:info:" + strconv.FormatInt(userID, 10)
	redis.Delete(cacheKey)

	var userinfo mysql.Users
	db.Model(&userinfo).
		Select("id, username, avatar_url, created_at, updated_at, nickname, deleted_at").
		Where("id = ?", userID).
		First(&userinfo)


	format.Success(c, "uploadAvatar", userinfo)
}
