// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/my_jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	return []app.HandlerFunc{my_jwt.AuthMiddleware.MiddlewareFunc()}
}

func _registerMw() []app.HandlerFunc {
	return nil
}

func _user_idMw() []app.HandlerFunc {
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	// your code...
	return nil
}
