// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	format "VideoWeb/biz/handler/common_response_format"
	example0 "VideoWeb/biz/model/common/example"
	example "VideoWeb/biz/model/video/example"
	"context"
	"fmt"
	"net/http"
	"strconv"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
)

// SearchVideos .
// @router /api/videos/search [GET]
func SearchVideos(ctx context.Context, c *app.RequestContext) {
	var req example.SearchVideoRequest
	if err := c.BindQuery(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	if req.Keyword == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, fmt.Sprintf("keyword is empty"))
		return
	}

	page := int(req.Page)
	pageSize := int(req.PageSize)
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 50 {
		pageSize = 10
	}

	db := mysql.GetDB()
	var videos []mysql.Videos
	var total int64

	query := db.Model(&mysql.Videos{})
	query = query.Where("title LIKE ? OR description LIKE ?", "%"+req.Keyword+"%", "%"+req.Keyword+"%")

	query.Count(&total)

	switch req.Sort {
	case "views":
		query = query.Order("views DESC")
	case "likes":
		query = query.Order("likes DESC")
	default:
		query = query.Order("created_at DESC")
	}

	offset := (page - 1) * pageSize
	query.Offset(offset).Limit(pageSize).Find(&videos)

	//// 构建返回列表
	//items := make([]map[string]interface{}, len(videos))
	//for i, v := range videos {
	//	items[i] = map[string]interface{}{
	//		"id":            strconv.FormatInt(int64(v.ID), 10),
	//		"user_id":       strconv.FormatInt(v.UserID, 10),
	//		"video_url":     v.VideoURL,
	//		"title":         v.Title,
	//		"description":   v.Description,
	//		"visit_count":   v.Views,
	//		"like_count":    v.Likes,
	//		"comment_count": v.Comments,
	//		"created_at":    v.CreatedAt.Format("2006-01-02 15:04:05"),
	//		"updated_at":    v.UpdatedAt.Format("2006-01-02 15:04:05"),
	//		"deleted_at":    "",
	//	}
	//	if v.DeletedAt != nil {
	//		items[i]["deleted_at"] = v.DeletedAt.Format("2006-01-02 15:04:05")
	//	}
	//}
	format.Success(c, "SearchVideo", map[string]interface{}{
		"items": videos,
		"total": total,
	})
}

// GetHotVideos .
// @router /api/videos/hot [GET]
func GetHotVideos(ctx context.Context, c *app.RequestContext) {
	var req example.HotVideoRequest
	if err := c.BindQuery(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}
	limit := int(req.Limit)
	if limit < 1 || limit > 100 {
		limit = 10
	}
	page := int(req.Page)
	if page < 1 {
		page = 1
	}

	db := mysql.GetDB()
	var videos []mysql.Videos

	query := db.Model(&mysql.Videos{})

	now := time.Now()
	switch req.Type {
	case "day":
		query = query.Where("created_at >= ?", now.AddDate(0, 0, -1))
	case "week":
		query = query.Where("created_at >= ?", now.AddDate(0, 0, -7))
	case "month":
		query = query.Where("created_at >= ?", now.AddDate(0, -1, 0))
	}

	offset := (page - 1) * limit
	query.Order("views DESC").Offset(offset).Limit(limit).Find(&videos)

	format.Success(c, "SearchVideo", map[string]interface{}{
		"items": videos,
	})
}

// GetUserVideos .
// @router /api/users/:user_id/videos [GET]
func GetUserVideos(ctx context.Context, c *app.RequestContext) {
	// 从路径参数获取用户ID
	userIDStr := c.Param("user_id")
	if userIDStr == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "user_id is not found")
		return
	}

	userID, err := strconv.ParseInt(userIDStr, 10, 64)
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, err.Error())
		return
	}

	var req example.UserVideoListRequest
	if err := c.BindQuery(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	page := int(req.Page)
	pageSize := int(req.PageSize)
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 50 {
		pageSize = 10
	}

	db := mysql.GetDB()

	// 验证用户是否存在
	var user mysql.Users
	if err := db.First(&user, userID).Error; err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, err.Error())
		return
	}

	var videos []mysql.Videos
	var total int64

	query := db.Model(&mysql.Videos{}).Where("user_id = ?", userID)
	query.Count(&total)

	offset := (page - 1) * pageSize
	query.Order("created_at DESC").Offset(offset).Limit(pageSize).Find(&videos)

	format.Success(c, "SearchVideo", map[string]interface{}{
		"items": videos,
		"total": total,
	})
}
