// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	"VideoWeb/biz/dal/redis"
	format "VideoWeb/biz/handler/common_response_format"
	example0 "VideoWeb/biz/model/common/example"
	example "VideoWeb/biz/model/video/example"
	"context"
	"fmt"
	"net/http"
	"strconv"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
)

// SearchVideos .
// @router /api/videos/search [GET]
func SearchVideos(ctx context.Context, c *app.RequestContext) {
	var req example.SearchVideoRequest
	if err := c.BindQuery(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	if req.Keyword == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, fmt.Sprintf("keyword is empty"))
		return
	}

	page := int(req.Page)
	pageSize := int(req.PageSize)
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 50 {
		pageSize = 10
	}

	cacheKey := fmt.Sprintf("video:search:%s:%s:%d:%d", req.Keyword, req.Sort, page, pageSize)

	type SearchResult struct {
		Items []mysql.Videos
		Total int64
	}
	var cachedResult SearchResult
	err := redis.GetJSON(cacheKey, &cachedResult)
	if err == nil && len(cachedResult.Items) > 0 {
		format.Success(c, "SearchVideo", map[string]interface{}{
			"items": cachedResult.Items,
			"total": cachedResult.Total,
		})
		return
	}

	db := mysql.GetDB()
	var videos []mysql.Videos
	var total int64

	query := db.Model(&mysql.Videos{})
	query = query.Where("title LIKE ? OR description LIKE ?", "%"+req.Keyword+"%", "%"+req.Keyword+"%")

	query.Count(&total)

	switch req.Sort {
	case "views":
		query = query.Order("views DESC")
	case "likes":
		query = query.Order("likes DESC")
	default:
		query = query.Order("created_at DESC")
	}

	offset := (page - 1) * pageSize
	query.Offset(offset).Limit(pageSize).Find(&videos)

	result := SearchResult{
		Items: videos,
		Total: total,
	}
	redis.SetJSON(cacheKey, result, 5*time.Minute)

	format.Success(c, "SearchVideo", map[string]interface{}{
		"items": videos,
		"total": total,
	})
}

// GetHotVideos .
// @router /api/videos/hot [GET]
func GetHotVideos(ctx context.Context, c *app.RequestContext) {
	var req example.HotVideoRequest
	if err := c.BindQuery(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}
	limit := int(req.Limit)
	if limit < 1 || limit > 100 {
		limit = 10
	}
	page := int(req.Page)
	if page < 1 {
		page = 1
	}

	cacheKey := fmt.Sprintf("video:hot:%s:%d:%d", req.Type, page, limit)

	var cachedVideos []mysql.Videos
	err := redis.GetJSON(cacheKey, &cachedVideos)
	if err == nil && len(cachedVideos) > 0 {
		format.Success(c, "SearchVideo", map[string]interface{}{
			"items": cachedVideos,
		})
		return
	}

	db := mysql.GetDB()
	var videos []mysql.Videos

	query := db.Model(&mysql.Videos{})

	now := time.Now()
	switch req.Type {
	case "day":
		query = query.Where("created_at >= ?", now.AddDate(0, 0, -1))
	case "week":
		query = query.Where("created_at >= ?", now.AddDate(0, 0, -7))
	case "month":
		query = query.Where("created_at >= ?", now.AddDate(0, -1, 0))
	}

	offset := (page - 1) * limit
	query.Order("views DESC").Offset(offset).Limit(limit).Find(&videos)

	redis.SetJSON(cacheKey, videos, 10*time.Minute)

	format.Success(c, "SearchVideo", map[string]interface{}{
		"items": videos,
	})
}

// GetUserVideos .
// @router /api/users/:user_id/videos [GET]
func GetUserVideos(ctx context.Context, c *app.RequestContext) {
	userIDStr := c.Param("user_id")
	if userIDStr == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "user_id is not found")
		return
	}

	userID, err := strconv.ParseInt(userIDStr, 10, 64)
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, err.Error())
		return
	}

	var req example.UserVideoListRequest
	if err := c.BindQuery(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	page := int(req.Page)
	pageSize := int(req.PageSize)
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 50 {
		pageSize = 10
	}

	cacheKey := fmt.Sprintf("video:user:%d:%d:%d", userID, page, pageSize)

	type UserVideoResult struct {
		Items []mysql.Videos
		Total int64
	}
	var cachedResult UserVideoResult
	err = redis.GetJSON(cacheKey, &cachedResult)
	if err == nil && len(cachedResult.Items) > 0 {
		format.Success(c, "SearchVideo", map[string]interface{}{
			"items": cachedResult.Items,
			"total": cachedResult.Total,
		})
		return
	}

	db := mysql.GetDB()

	var user mysql.Users
	if err := db.First(&user, userID).Error; err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, err.Error())
		return
	}

	var videos []mysql.Videos
	var total int64

	query := db.Model(&mysql.Videos{}).Where("user_id = ?", userID)
	query.Count(&total)

	offset := (page - 1) * pageSize
	query.Order("created_at ASC").Offset(offset).Limit(pageSize).Find(&videos)

	result := UserVideoResult{
		Items: videos,
		Total: total,
	}
	redis.SetJSON(cacheKey, result, 10*time.Minute)

	format.Success(c, "SearchVideo", map[string]interface{}{
		"items": videos,
		"total": total,
	})
}
