// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	format "VideoWeb/biz/handler/common_response_format"
	"context"
	"net/http"
	"strconv"

	example0 "VideoWeb/biz/model/common/example"
	example "VideoWeb/biz/model/interaction/example"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetCommentList .
// @router /api/videos/:video_id/comments [GET]
func GetCommentList(ctx context.Context, c *app.RequestContext) {
	videoIDStr := c.Param("video_id")
	if videoIDStr == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "video_id is not found")
		return
	}

	videoID, err := strconv.ParseInt(videoIDStr, 10, 64)
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, err.Error())
		return
	}

	var req example.CommentListRequest
	if err := c.BindQuery(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	page := int(req.Page)
	pageSize := int(req.PageSize)
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 50 {
		pageSize = 10
	}

	db := mysql.GetDB()

	var video mysql.Videos
	if err := db.First(&video, videoID).Error; err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_VIDEO_NOT_EXIST, "video is not exist")
		return
	}

	var comments []mysql.Comments
	var total int64

	query := db.Model(&mysql.Comments{}).Where("video_id = ? AND parent_id = 0", videoID)
	query.Count(&total)

	offset := (page - 1) * pageSize
	query.Order("created_at DESC").Offset(offset).Limit(pageSize).Find(&comments)

	format.Success(c, "GetCommentList", map[string]interface{}{
		"items": comments,
		"total": total,
	})
}
