// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	"VideoWeb/biz/dal/redis"
	format "VideoWeb/biz/handler/common_response_format"
	"context"
	"fmt"
	"net/http"
	"strconv"

	example0 "VideoWeb/biz/model/common/example"
	example "VideoWeb/biz/model/interaction/example"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/jwt"
	"github.com/jinzhu/gorm"
)

// CreateComment .
// @router /api/comments [POST]
func CreateComment(ctx context.Context, c *app.RequestContext) {
	claims := jwt.ExtractClaims(ctx, c)
	tokenUserID, ok := claims["ID"].(float64)
	if !ok {
		format.Fail(c, http.StatusUnauthorized, example0.ErrorCode_USER_NOT_LOGIN, "user not login")
		return
	}
	userID := int64(tokenUserID)

	var req example.CreateCommentRequest
	if err := c.BindForm(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	if req.Content == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "content is empty")
		return
	}

	db := mysql.GetDB()

	var video mysql.Videos
	if err := db.First(&video, req.VideoID).Error; err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_VIDEO_NOT_EXIST, "video is not exist")
		return
	}

	comment := mysql.Comments{
		UserID:   userID,
		VideoID:  req.VideoID,
		ParentID: req.ParentID,
		Content:  req.Content,
		Likes:    0,
	}

	if err := db.Table("comments").Create(&comment).Error; err != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "create comment failed")
		return
	}

	db.Model(&mysql.Videos{}).Where("id = ?", req.VideoID).UpdateColumn("comments", gorm.Expr("comments + ?", 1))

	cacheKey := fmt.Sprintf("comment:list:%d:*", req.VideoID)
	redis.DeleteByPattern(cacheKey)

	format.Success(c, "CreateComment", nil)
}

// DeleteComment .
// @router /api/comments/:comment_id [DELETE]
func DeleteComment(ctx context.Context, c *app.RequestContext) {
	claims := jwt.ExtractClaims(ctx, c)
	tokenUserID, ok := claims["ID"].(float64)
	if !ok {
		format.Fail(c, http.StatusUnauthorized, example0.ErrorCode_USER_NOT_LOGIN, "user not login")
		return
	}
	userID := int64(tokenUserID)

	commentIDStr := c.Param("comment_id")
	if commentIDStr == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "comment_id is not found")
		return
	}

	commentID, err := strconv.ParseInt(commentIDStr, 10, 64)
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, err.Error())
		return
	}

	db := mysql.GetDB()

	var comment mysql.Comments
	if err := db.Table("comments").First(&comment, commentID).Error; err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_COMMENT_NOT_EXIST, err.Error()+"comment is not exist")
		return
	}

	if comment.UserID != userID {
		format.Fail(c, http.StatusForbidden, example0.ErrorCode_OPERATION_FORBIDDEN, "cannot delete other's comment")
		return
	}

	if err := db.Table("comments").Delete(&comment).Error; err != nil {
		format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, err.Error()+"delete comment failed")
		return
	}

	db.Model(&mysql.Videos{}).Where("id = ?", comment.VideoID).UpdateColumn("comments", gorm.Expr("comments - ?", 1))

	cacheKey := fmt.Sprintf("comment:list:%d:*", comment.VideoID)
	redis.DeleteByPattern(cacheKey)

	format.Success(c, "DeleteComment", nil)
}
