// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	"VideoWeb/biz/dal/redis"
	format "VideoWeb/biz/handler/common_response_format"
	"context"
	"fmt"
	"net/http"
	"strconv"
	"time"
	"log"
	example0 "VideoWeb/biz/model/common/example"
	example "VideoWeb/biz/model/interaction/example"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetCommentList .
// @router /api/videos/:video_id/comments [GET]
func GetCommentList(ctx context.Context, c *app.RequestContext) {
	videoIDStr := c.Param("video_id")
	if videoIDStr == "" {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "video_id is not found")
		return
	}

	videoID, err := strconv.ParseInt(videoIDStr, 10, 64)
	if err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, err.Error())
		return
	}

	var req example.CommentListRequest
	if err := c.BindQuery(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	page := int(req.Page)
	pageSize := int(req.PageSize)
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 50 {
		pageSize = 10
	}

	cacheKey := fmt.Sprintf("comment:list:%d:%d:%d", videoID, page, pageSize)

	type CommentListResult struct {
		Items []mysql.Comments
		Total int64
	}
	var cachedResult CommentListResult
	err = redis.GetJSON(cacheKey, &cachedResult)
	if err == nil {
		format.Success(c, "GetCommentList", map[string]interface{}{
			"items": cachedResult.Items,
			"total": cachedResult.Total,
		})
		return
	}
	if err.Error() != "redis not connected"  {
		log.Printf("Redis GetJSON error: %v", err)
	}
	
	isNull, _ := redis.IsNullCache(cacheKey)
	if isNull {
		format.Success(c, "GetCommentList", map[string]interface{}{
			"items": []mysql.Comments{},
			"total": 0,
		})
		return
	}

	db := mysql.GetDB()

	var video mysql.Videos
	if err := db.First(&video, videoID).Error; err != nil {
		redis.SetNullCache(cacheKey, 5*time.Minute)
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_VIDEO_NOT_EXIST, "video is not exist")
		return
	}

	var comments []mysql.Comments
	var total int64

	query := db.Model(&mysql.Comments{}).Where("video_id = ? AND parent_id = 0", videoID)
	query.Count(&total)

	offset := (page - 1) * pageSize
	query.Order("created_at DESC").Offset(offset).Limit(pageSize).Find(&comments)

	result := CommentListResult{
		Items: comments,
		Total: total,
	}
	if len(comments) == 0 {
		redis.SetNullCache(cacheKey, 5*time.Minute)
	} else {
		redis.SetJSON(cacheKey, result, 5*time.Minute)
	}

	format.Success(c, "GetCommentList", map[string]interface{}{
		"items": comments,
		"total": total,
	})
}
