// Code generated by hertz generator.

package example

import (
	"VideoWeb/biz/dal/mysql"
	"VideoWeb/biz/dal/redis"
	format "VideoWeb/biz/handler/common_response_format"
	"context"
	"fmt"
	"net/http"
	"strconv"
	"time"

	example0 "VideoWeb/biz/model/common/example"
	example "VideoWeb/biz/model/interaction/example"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/jwt"
	"github.com/jinzhu/gorm"
)

// LikeAction .
// @router /api/likes [POST]
func LikeAction(ctx context.Context, c *app.RequestContext) {
	claims := jwt.ExtractClaims(ctx, c)
	tokenUserID, ok := claims["ID"].(float64)
	if !ok {
		format.Fail(c, http.StatusUnauthorized, example0.ErrorCode_USER_NOT_LOGIN, "user not login")
		return
	}
	userID := int64(tokenUserID)

	var req example.LikeRequest
	if err := c.BindForm(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	db := mysql.GetDB()

	if req.Type == 1 {
		var video mysql.Videos
		if err := db.First(&video, req.TargetID).Error; err != nil {
			format.Fail(c, http.StatusBadRequest, example0.ErrorCode_VIDEO_NOT_EXIST, err.Error()+"video is not exist")
			return
		}
	} else if req.Type == 2 {
		var comment mysql.Comments
		if err := db.First(&comment, req.TargetID).Error; err != nil {
			format.Fail(c, http.StatusBadRequest, example0.ErrorCode_COMMENT_NOT_EXIST, err.Error()+"comment is not exist")
			return
		}
	} else {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "invalid type")
		return
	}

	likeKey := fmt.Sprintf("like:%d:%d:%d", userID, req.TargetID, req.Type)
	countKey := fmt.Sprintf("like:count:%d:%d", req.Type, req.TargetID)

	if req.Status {
		exists, _ := redis.Exists(likeKey)
		if exists {
			format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "already liked")
			return
		}

		var like mysql.Likes
		result := db.Where("user_id = ? AND target_id = ? AND type = ?", userID, req.TargetID, req.Type).First(&like)
		if result.Error == nil {
			format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "already liked")
			return
		}

		newLike := mysql.Likes{
			UserID:   userID,
			TargetID: req.TargetID,
			Type:     int(req.Type),
		}
		if err := db.Create(&newLike).Error; err != nil {
			format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "create like failed")
			return
		}

		redis.Set(likeKey, "1")
		redis.Incr(countKey)

		if req.Type == 1 {
			db.Model(&mysql.Videos{}).Where("id = ?", req.TargetID).UpdateColumn("likes", gorm.Expr("likes + ?", 1))
			redis.DeleteByPattern("video:*")
		} else {
			db.Model(&mysql.Comments{}).Where("id = ?", req.TargetID).UpdateColumn("likes", gorm.Expr("likes + ?", 1))
		}

		format.Success(c, "like", nil)
	} else {
		var like mysql.Likes
		result := db.Where("user_id = ? AND target_id = ? AND type = ?", userID, req.TargetID, req.Type).First(&like)
		if result.Error != nil {
			format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "not liked")
			return
		}

		if err := db.Delete(&like).Error; err != nil {
			format.Fail(c, http.StatusInternalServerError, example0.ErrorCode_PROGRESS_ERROR, "delete like failed")
			return
		}

		redis.Delete(likeKey)
		redis.Decr(countKey)

		if req.Type == 1 {
			db.Model(&mysql.Videos{}).Where("id = ?", req.TargetID).UpdateColumn("likes", gorm.Expr("likes - ?", 1))
			redis.DeleteByPattern("video:*")
		} else {
			db.Model(&mysql.Comments{}).Where("id = ?", req.TargetID).UpdateColumn("likes", gorm.Expr("likes - ?", 1))
		}

		format.Success(c, "unlike", nil)
	}
}

// GetLikeList .
// @router /api/likes/list [GET]
func GetLikeList(ctx context.Context, c *app.RequestContext) {
	var req example.LikeListRequest
	if err := c.BindQuery(&req); err != nil {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_REQUEST_ERROR, err.Error())
		return
	}

	db := mysql.GetDB()
	if req.Type == 1 {
		var video mysql.Videos
		if err := db.First(&video, req.TargetID).Error; err != nil {
			format.Fail(c, http.StatusBadRequest, example0.ErrorCode_VIDEO_NOT_EXIST, "video is not exist")
			return
		}
	} else if req.Type == 2 {
		var comment mysql.Comments
		if err := db.First(&comment, req.TargetID).Error; err != nil {
			format.Fail(c, http.StatusBadRequest, example0.ErrorCode_COMMENT_NOT_EXIST, "comment is not exist")
			return
		}
	} else {
		format.Fail(c, http.StatusBadRequest, example0.ErrorCode_PARAM_ERROR, "invalid type")
		return
	}

	page := int(req.Page)
	pageSize := int(req.PageSize)
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 50 {
		pageSize = 10
	}

	cacheKey := fmt.Sprintf("like:list:%d:%d:%d:%d", req.TargetID, req.Type, page, pageSize)

	type LikeListResult struct {
		Items []map[string]interface{}
		Total int64
	}
	var cachedResult LikeListResult
	err := redis.GetJSON(cacheKey, &cachedResult)
	if err == nil {
		format.Success(c, "GetLikeList", map[string]interface{}{
			"items": cachedResult.Items,
			"total": cachedResult.Total,
		})
		return
	}

	var likes []mysql.Likes
	var total int64

	query := db.Model(&mysql.Likes{}).Where("target_id = ? AND type = ?", req.TargetID, req.Type)
	query.Count(&total)

	offset := (page - 1) * pageSize
	query.Order("created_at DESC").Offset(offset).Limit(pageSize).Find(&likes)

	items := make([]map[string]interface{}, len(likes))
	for i, like := range likes {
		var user mysql.Users
		db.First(&user, like.UserID)

		items[i] = map[string]interface{}{
			"id":         strconv.FormatUint(uint64(like.ID), 10),
			"user_id":    strconv.FormatInt(like.UserID, 10),
			"target_id":  strconv.FormatInt(like.TargetID, 10),
			"type":       like.Type,
			"created_at": like.CreatedAt.Format("2006-01-02 15:04:05"),
			"user": map[string]interface{}{
				"id":        strconv.FormatUint(uint64(user.ID), 10),
				"username":  user.Username,
				"nickname":  user.Nickname,
				"avatarurl": user.Avatarurl,
			},
		}
	}

	result := LikeListResult{
		Items: items,
		Total: total,
	}
	redis.SetJSON(cacheKey, result, 5*time.Minute)

	format.Success(c, "GetLikeList", map[string]interface{}{
		"items": items,
		"total": total,
	})
}
